-- CREATE DATABASE
create DATABASE ABC_PVT_LTD;  -- THIS IS A QUERY TO CREATE A DATABASE 

-- ctrl+Enter

create database pqr_pvt_ltd;

create database xyz_pvt_ltd;

-- selecting the database
use abc_pvt_ltd;

-- creating the tables
create table employees(eid int,ename varchar(50),dept varchar(30),salary float);

-- description command
desc employees;

-- alter 
-- ADDING A NEW COLUMN (ADDED AT THE LAST BY DEFAULT)
-- ADDING 1 SINGLE COLUMN
ALTER TABLE EMPLOYEES
ADD COLUMN GENDER ENUM("MALE","FEMALE");

-- ADDING MULTIPLE COLUMNS (ADDED AT THE LAST BY DEFAULT)
ALTER TABLE EMPLOYEES
ADD COLUMN (AGE INT,MGR_ID INT); -- all should be added at the last
-- OR
ALTER TABLE EMPLOYEES
ADD COLUMN E_CODE INT,ADD COLUMN MGR_NAME VARCHAR(60);

-- ADDING THE COLUMNS AT THE 1ST POSITION
ALTER TABLE EMPLOYEES
ADD COLUMN ID INT FIRST;

-- ADDING THE COLUMNS AT A SPECIFIC POSITION
ALTER TABLE EMPLOYEES
ADD COLUMN EMP_ID INT AFTER ID;

-- alter table employees -> add columns (id ->first, mgr_name last, email after ename)
ALTER TABLE employees
ADD COLUMN ID INT FIRST, 
ADD COLUMN MGR_NAME VARCHAR(50), 
ADD COLUMN email VARCHAR(50) AFTER ENAME;

-- DROP COLUMN
ALTER TABLE EMPLOYEES
DROP COLUMN ID,DROP column EMP_ID;

-- MODIFY THE DATATYPE
ALTER TABLE EMPLOYEES
MODIFY COLUMN GENDER ENUM("MALE","FEMALE");

-- RENAME (TABLE)
-- EMPLOYEES WITH MYEMP
ALTER TABLE EMPLOYEES
RENAME TO MYEMP;
-- OR 
RENAME TABLE MYEMP
TO EMP_DETAILS;

-- RENAME (COLUMN)
ALTER TABLE emp_details
RENAME COLUMN ENAME TO FULLNAME;

-- RENAME THE TABLE EMP_DETAILS TO EMPLOYEES
-- RENAME COLUMN DEPT TO DEPARTMENT

-- DROP V/S TRUNCATE
-- DROP -> ENTIRE TABLE WITH ALL THE DATA IN IT IS GETTING DELETED
-- TRUNCATE -> TABLE WILL REMAIN AS IT IS BUT THE DATA INSIDE IT WIL GET DELETED

-- TRUNCATE -> DROP TABLE, CREATE TABLE

TRUNCATE TABLE EMP_DETAILS;
DROP TABLE EMP_DETAILS;


-- CREATING A TABLE FROM ANOTHER TABLE
SELECT * FROM employees;

CREATE TABLE EMP AS
(SELECT * FROM employees);

SELECT * FROM EMP;